# Generated by Django 3.2.20 on 2023-08-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand_colour_main', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_colour_secondary', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(default='GB', max_length=255)),
                ('currency', models.CharField(default='GBP', max_length=255)),
            ],
        ),
    ]
