# Generated by Django 3.2.20 on 2023-08-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='battery_percentage',
            field=models.IntegerField(null=True),
        ),
    ]
