# Generated by Django 3.2.20 on 2023-08-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0002_vehicle_battery_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='estimated_battery_increase_percentage',
            field=models.IntegerField(null=True),
        ),
    ]
